In [11]:
import pandas as pd

In [12]:
df = pd.read_excel("Sample - cleaned Superstore.xlsx")

In [13]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Revenue
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,523.9200
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2195.8200
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,29.2400
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,4787.8875
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,44.7360

In [14]:
df.shape

(9994, 22)

In [15]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit', 'Revenue'],
      dtype='str')

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Order Date     9994 non-null   datetime64[us]
 3   Ship Date      9994 non-null   datetime64[us]
 4   Ship Mode      9994 non-null   str
 5   Customer ID    9994 non-null   str
 6   Customer Name  9994 non-null   str
 7   Segment        9994 non-null   str
 8   Country        9994 non-null   str
 9   City           9994 non-null   str
 10  State          9994 non-null   str
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   str
 13  Product ID     9994 non-null   str
 14  Category       9994 non-null   str
 15  Sub-Category   9994 non-null   str
 16  Product Name   9994 non-null   str
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
 21  Revenue        9994 non-null   float64
dtypes: datetime64[us](2), float64(4), int64(3), str(13)
memory usage: 1.7 MB

In [17]:
import sqlite3
conn = sqlite3.connect("Superstor.db")
df.to_sql("orders", conn, if_exists="replace", index=False)
print("Database ban gaya aur data load ho gaya!")

Database ban gaya aur data load ho gaya!

In [18]:
query = "SELECT * FROM orders LIMIT 5;"
pd.read_sql(query, conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Revenue
0,1,CA-2016-152156,2016-11-08 00:00:00,2016-11-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,523.9200
1,2,CA-2016-152156,2016-11-08 00:00:00,2016-11-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2195.8200
2,3,CA-2016-138688,2016-06-12 00:00:00,2016-06-16 00:00:00,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,29.2400
3,4,US-2015-108966,2015-10-11 00:00:00,2015-10-18 00:00:00,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,4787.8875
4,5,US-2015-108966,2015-10-11 00:00:00,2015-10-18 00:00:00,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,44.7360

In [19]:
query= """
SELECT 
   ROUND(SUM(REVENUE), 2) AS Total_revenue,
   ROUND(SUM(PROFIT), 2) AS TOTAL_PROFIT,
   ROUND(SUM(PROFIT)*100.0/ SUM(REVENUE), 2) AS PROFTI_MARGIN_PERCENTAGE
   fROM Orders;
"""
pd.read_sql(query, conn)

   Total_revenue  TOTAL_PROFIT  PROFTI_MARGIN_PERCENTAGE
0    11488062.07     286397.02                      2.49

In [22]:
query="""
SELECT
    Category, "Sub-Category",
    ROUND(SUM(REVENUE), 2) AS TOTAL_REVENUE,
    ROUND(SUM(PROFIT)< 2) AS TOTAL_PROFIT
FROM ORDERS
GROUP BY Category, "Sub-Category"
ORDER BY TOTAL_REVENUE DESC;
"""
pd.read_sql(query, conn)

           Category Sub-Category  TOTAL_REVENUE  TOTAL_PROFIT
0         Furniture       Chairs     1662757.97           0.0
1        Technology       Phones     1628827.96           0.0
2         Furniture       Tables     1144514.33           1.0
3   Office Supplies      Storage     1099229.48           0.0
4   Office Supplies      Binders     1013454.13           0.0
5        Technology     Machines      914789.88           0.0
6        Technology  Accessories      878922.52           0.0
7        Technology      Copiers      657721.17           0.0
8         Furniture    Bookcases      597826.12           1.0
9   Office Supplies   Appliances      547368.45           0.0
10        Furniture  Furnishings      454116.81           0.0
11  Office Supplies        Paper      389404.41           0.0
12  Office Supplies     Supplies      201235.83           1.0
13  Office Supplies          Art      136021.11           0.0
14  Office Supplies    Envelopes       74179.35           0.0
15  Office Supplies       Labels       70634.76           0.0
16  Office Supplies    Fasteners       17057.79           0.0

In [23]:
df['Profit'].dtype

dtype('float64')

In [24]:
df['Profit'].head(10)

0     41.9136
1    219.5820
2      6.8714
3   -383.0310
4      2.5164
5     14.1694
6      1.9656
7     90.7152
8      5.7825
9     34.4700
Name: Profit, dtype: float64

In [25]:
query = "SELECT Profit FROM orders LIMIT 10;"
pd.read_sql(query, conn)

     Profit
0   41.9136
1  219.5820
2    6.8714
3 -383.0310
4    2.5164
5   14.1694
6    1.9656
7   90.7152
8    5.7825
9   34.4700

In [26]:
pd.read_sql("PRAGMA table_info(orders);", conn)

    cid           name       type  notnull dflt_value  pk
0     0         Row ID    INTEGER        0       None   0
1     1       Order ID       TEXT        0       None   0
2     2     Order Date  TIMESTAMP        0       None   0
3     3      Ship Date  TIMESTAMP        0       None   0
4     4      Ship Mode       TEXT        0       None   0
5     5    Customer ID       TEXT        0       None   0
6     6  Customer Name       TEXT        0       None   0
7     7        Segment       TEXT        0       None   0
8     8        Country       TEXT        0       None   0
9     9           City       TEXT        0       None   0
10   10          State       TEXT        0       None   0
11   11    Postal Code    INTEGER        0       None   0
12   12         Region       TEXT        0       None   0
13   13     Product ID       TEXT        0       None   0
14   14       Category       TEXT        0       None   0
15   15   Sub-Category       TEXT        0       None   0
16   16   Product Name       TEXT        0       None   0
17   17          Sales       REAL        0       None   0
18   18       Quantity    INTEGER        0       None   0
19   19       Discount       REAL        0       None   0
20   20         Profit       REAL        0       None   0
21   21        Revenue       REAL        0       None   0

In [27]:
import os

conn.close()  

if os.path.exists("superstore.db"):
    os.remove("superstore.db")  

conn = sqlite3.connect("superstore.db") 
df.to_sql("orders", conn, if_exists="replace", index=False)

print("Fresh database ban gaya!")

Fresh database ban gaya!

In [28]:
query = """
SELECT 
    Category,
    "Sub-Category",
    ROUND(SUM(Revenue), 2) AS Total_Revenue,
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM orders
GROUP BY Category, "Sub-Category"
ORDER BY Total_Revenue DESC;
"""
pd.read_sql(query, conn)

           Category Sub-Category  Total_Revenue  Total_Profit
0         Furniture       Chairs     1662757.97      26590.17
1        Technology       Phones     1628827.96      44515.73
2         Furniture       Tables     1144514.33     -17725.48
3   Office Supplies      Storage     1099229.48      21278.83
4   Office Supplies      Binders     1013454.13      30221.76
5        Technology     Machines      914789.88       3384.76
6        Technology  Accessories      878922.52      41936.64
7        Technology      Copiers      657721.17      55617.82
8         Furniture    Bookcases      597826.12      -3472.56
9   Office Supplies   Appliances      547368.45      18138.01
10        Furniture  Furnishings      454116.81      13059.14
11  Office Supplies        Paper      389404.41      34053.57
12  Office Supplies     Supplies      201235.83      -1189.10
13  Office Supplies          Art      136021.11       6527.79
14  Office Supplies    Envelopes       74179.35       6964.18
15  Office Supplies       Labels       70634.76       5546.25
16  Office Supplies    Fasteners       17057.79        949.52

In [29]:
query = """
SELECT 
    Category,
    "Sub-Category",
    ROUND(SUM(Revenue), 2) AS Total_Revenue,
    ROUND(SUM(Profit), 2) AS Total_Profit,
    ROUND(SUM(Profit) * 100.0 / SUM(Revenue), 2) AS Profit_Margin_Percent
FROM orders
GROUP BY Category, "Sub-Category"
HAVING SUM(Profit) < 0
ORDER BY Total_Profit ASC;
"""
pd.read_sql(query, conn)

,Category,Sub-Category,Total_Revenue,Total_Profit,Profit_Margin_Percent
0,Furniture,Tables,1144514.33,-17725.48,-1.55
1,Furniture,Bookcases,597826.12,-3472.56,-0.58
2,Office Supplies,Supplies,201235.83,-1189.10,-0.59

In [30]:
query = """
SELECT 
    Category,
    "Sub-Category",
    ROUND(AVG(Discount), 3) AS Avg_Discount,
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM orders
GROUP BY Category, "Sub-Category"
ORDER BY Avg_Discount DESC;
"""
pd.read_sql(query, conn)

           Category Sub-Category  Avg_Discount  Total_Profit
0   Office Supplies      Binders         0.372      30221.76
1        Technology     Machines         0.306       3384.76
2         Furniture       Tables         0.261     -17725.48
3         Furniture    Bookcases         0.211      -3472.56
4         Furniture       Chairs         0.170      26590.17
5   Office Supplies   Appliances         0.167      18138.01
6        Technology      Copiers         0.162      55617.82
7        Technology       Phones         0.155      44515.73
8         Furniture  Furnishings         0.138      13059.14
9   Office Supplies    Fasteners         0.082        949.52
10  Office Supplies    Envelopes         0.080       6964.18
11       Technology  Accessories         0.078      41936.64
12  Office Supplies     Supplies         0.077      -1189.10
13  Office Supplies          Art         0.075       6527.79
14  Office Supplies        Paper         0.075      34053.57
15  Office Supplies      Storage         0.075      21278.83
16  Office Supplies       Labels         0.069       5546.25

In [31]:
query = """
SELECT 
    "Product Name",
    Sales,
    Quantity,
    Discount,
    Profit,
    Revenue
FROM orders
WHERE "Sub-Category" = 'Supplies'
ORDER BY Profit ASC
LIMIT 15;
"""
pd.read_sql(query, conn)

,Product Name,Sales,Quantity,Discount,Profit,Revenue
0,Martin Yale Chadless Opener Electric Letter Op...,4663.736,7,0.2,-1049.3406,32646.152
1,High Speed Automatic Electric Letter Opener,3930.072,3,0.2,-786.0144,11790.216
2,Martin Yale Chadless Opener Electric Letter Op...,1332.496,2,0.2,-299.8116,2664.992
3,Premier Automatic Letter Opener,961.480,5,0.2,-204.3145,4807.400
4,Premier Automatic Letter Opener,769.184,4,0.2,-163.4516,3076.736
5,Martin Yale Chadless Opener Electric Letter Op...,666.248,1,0.2,-149.9058,666.248
6,Premier Automatic Letter Opener,384.592,2,0.2,-81.7258,769.184
7,Compact Automatic Electric Letter Opener,286.344,3,0.2,-64.4274,859.032
8,Compact Automatic Electric Letter Opener,190.896,2,0.2,-42.9516,381.792
9,Premier Electric Letter Opener,185.376,2,0.2,-34.7580,370.752
10,Premier Electric Letter Opener,185.376,2,0.2,-34.7580,370.752
11,Premier Electric Letter Opener,185.376,2,0.2,-34.7580,370.752
12,Stiletto Hand Letter Openers,69.120,9,0.2,-14.6880,622.080
13,Martin-Yale Premier Letter Opener,51.520,5,0.2,-10.9480,257.600
14,Stiletto Hand Letter Openers,23.040,3,0.2,-4.8960,69.120

In [32]:
query = """
SELECT 
    Discount,
    COUNT(*) AS Order_Count,
    ROUND(SUM(Profit), 2) AS Total_Profit,
    ROUND(AVG(Profit), 2) AS Avg_Profit_Per_Order
FROM orders
WHERE "Sub-Category" = 'Supplies'
GROUP BY Discount
ORDER BY Discount;
"""
pd.read_sql(query, conn)

   Discount  Order_Count  Total_Profit  Avg_Profit_Per_Order
0       0.0          117       1718.39                 14.69
1       0.2           73      -2907.49                -39.83

In [33]:
query = """
SELECT 
    CASE 
        WHEN Discount = 0 THEN '0% (No Discount)'
        WHEN Discount > 0 AND Discount <= 0.1 THEN '1-10%'
        WHEN Discount > 0.1 AND Discount <= 0.2 THEN '11-20%'
        WHEN Discount > 0.2 AND Discount <= 0.3 THEN '21-30%'
        ELSE '30%+'
    END AS Discount_Band,
    COUNT(*) AS Order_Count,
    ROUND(SUM(Profit), 2) AS Total_Profit,
    ROUND(AVG(Profit), 2) AS Avg_Profit_Per_Order
FROM orders
GROUP BY Discount_Band
ORDER BY MIN(Discount);
"""
pd.read_sql(query, conn)

      Discount_Band  Order_Count  Total_Profit  Avg_Profit_Per_Order
0  0% (No Discount)         4798     320987.60                 66.90
1             1-10%           94       9029.18                 96.06
2            11-20%         3709      91756.30                 24.74
3            21-30%          227     -10369.28                -45.68
4              30%+         1166    -125006.78               -107.21

In [34]:
query = """
SELECT 
    Region,
    COUNT(*) AS Order_Count,
    ROUND(SUM(Revenue), 2) AS Total_Revenue,
    ROUND(SUM(Profit), 2) AS Total_Profit,
    ROUND(SUM(Profit) * 100.0 / SUM(Revenue), 2) AS Profit_Margin_Percent
FROM orders
GROUP BY Region
ORDER BY Total_Profit DESC;
"""
pd.read_sql(query, conn)

    Region  Order_Count  Total_Revenue  Total_Profit  Profit_Margin_Percent
0     West         3203     3595227.52     108418.45                   3.02
1     East         2848     3379326.25      91522.78                   2.71
2    South         1620     2037675.35      46749.43                   2.29
3  Central         2323     2475832.94      39706.36                   1.60

In [35]:
query = """
SELECT 
    State,
    ROUND(SUM(Revenue), 2) AS Total_Revenue,
    ROUND(SUM(Profit), 2) AS Total_Profit,
    ROUND(SUM(Profit) * 100.0 / SUM(Revenue), 2) AS Profit_Margin_Percent
FROM orders
GROUP BY State
ORDER BY Total_Profit ASC
LIMIT 10;
"""
pd.read_sql(query, conn)

            State  Total_Revenue  Total_Profit  Profit_Margin_Percent
0           Texas      834088.33     -25729.36                  -3.08
1            Ohio      362533.80     -16971.38                  -4.68
2    Pennsylvania      602126.96     -15559.96                  -2.58
3        Illinois      365084.29     -12607.89                  -3.45
4  North Carolina      282777.54      -7490.91                  -2.65
5        Colorado      145591.12      -6527.86                  -4.48
6       Tennessee      158654.90      -5341.69                  -3.37
7         Arizona      170003.38      -3427.92                  -2.02
8         Florida      472091.28      -3399.30                  -0.72
9          Oregon       79009.06      -1190.47                  -1.51

In [36]:
query = """
SELECT 
    State,
    CASE 
        WHEN Discount = 0 THEN '0% (No Discount)'
        WHEN Discount > 0 AND Discount <= 0.1 THEN '1-10%'
        WHEN Discount > 0.1 AND Discount <= 0.2 THEN '11-20%'
        WHEN Discount > 0.2 AND Discount <= 0.3 THEN '21-30%'
        ELSE '30%+'
    END AS Discount_Band,
    COUNT(*) AS Order_Count,
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM orders
WHERE State IN ('Texas', 'Ohio')
GROUP BY State, Discount_Band
ORDER BY State, MIN(Discount);
"""
pd.read_sql(query, conn)

   State Discount_Band  Order_Count  Total_Profit
0   Ohio        11-20%          290       3255.84
1   Ohio        21-30%           23       -649.35
2   Ohio          30%+          156     -19577.86
3  Texas        11-20%          570       8225.93
4  Texas        21-30%           94      -4732.33
5  Texas          30%+          321     -29222.96

In [37]:
query = """
SELECT 
    strftime('%Y', "Order Date") AS Year,
    strftime('%m', "Order Date") AS Month,
    ROUND(SUM(Revenue), 2) AS Total_Revenue,
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM orders
GROUP BY Year, Month
ORDER BY Year, Month;
"""
pd.read_sql(query, conn)

    Year Month  Total_Revenue  Total_Profit
0   2014    01       73744.13       2450.19
1   2014    02       19603.21        862.31
2   2014    03      292309.55        498.73
3   2014    04      146423.00       3488.84
4   2014    05      117540.56       2738.71
5   2014    06      170963.46       4976.52
6   2014    07      158392.56       -841.48
7   2014    08      137450.20       5318.10
8   2014    09      417139.72       8328.10
9   2014    10      159024.73       3448.26
10  2014    11      383642.56       9292.13
11  2014    12      392050.05       8983.57
12  2015    01      129297.85      -3281.01
13  2015    02       52934.74       2813.85
14  2015    03      199589.64       9732.10
15  2015    04      143593.75       4187.50
16  2015    05      167456.82       4667.87
17  2015    06       96522.29       3335.56
18  2015    07      149333.73       3288.65
19  2015    08      186724.54       5355.81
20  2015    09      334991.38       8209.16
21  2015    10      140458.93       2817.37
22  2015    11      376714.51      12474.79
23  2015    12      407283.20       8016.97
24  2016    01       98322.40       2824.82
25  2016    02      104344.62       5004.58
26  2016    03      237420.09       3611.97
27  2016    04      191368.70       2977.81
28  2016    05      296416.98       8662.15
29  2016    06      185399.31       4750.38
30  2016    07      180687.70       4432.88
31  2016    08      160060.51       2062.07
32  2016    09      346144.09       9328.66
33  2016    10      300826.26      16243.14
34  2016    11      389646.53       4011.41
35  2016    12      559420.17      17885.31
36  2017    01      203832.62       7140.44
37  2017    02       87762.98       1613.87
38  2017    03      251524.69      14751.89
39  2017    04      146195.93        933.29
40  2017    05      216459.76       6342.58
41  2017    06      267986.18       8223.34
42  2017    07      213810.04       6952.62
43  2017    08      393875.73       9040.96
44  2017    09      417519.86      10991.56
45  2017    10      397186.51       9275.28
46  2017    11      599996.23       9690.10
47  2017    12      388669.08       8483.35

In [38]:
query = """
SELECT 
    Segment,
    COUNT(*) AS Order_Count,
    ROUND(SUM(Revenue), 2) AS Total_Revenue,
    ROUND(SUM(Profit), 2) AS Total_Profit,
    ROUND(SUM(Profit) * 100.0 / SUM(Revenue), 2) AS Profit_Margin_Percent,
    ROUND(AVG(Discount), 3) AS Avg_Discount
FROM orders
GROUP BY Segment
ORDER BY Total_Profit DESC;
"""
pd.read_sql(query, conn)

,Segment,Order_Count,Total_Revenue,Total_Profit,Profit_Margin_Percent,Avg_Discount
0,Consumer,5191,5819347.40,134119.21,2.30,0.158
1,Corporate,3020,3516107.67,91979.13,2.62,0.158
2,Home Office,1783,2152607.00,60298.68,2.80,0.147

In [39]:
query = """
SELECT 
    "Customer Name",
    COUNT(*) AS Order_Count,
    ROUND(SUM(Revenue), 2) AS Total_Revenue,
    ROUND(SUM(Profit), 2) AS Total_Profit
FROM orders
GROUP BY "Customer Name"
ORDER BY Total_Profit DESC
LIMIT 10;
"""
pd.read_sql(query, conn)

          Customer Name  Order_Count  Total_Revenue  Total_Profit
0          Tamara Chand           12       92602.57       8981.32
1          Raymond Buch           18       61131.75       6976.10
2          Sanjit Chand           22       62679.33       5757.41
3          Hunter Lopez           11       44296.45       5622.43
4         Adrian Barton           20      143857.71       5444.81
5          Tom Ashbrook           10       66671.70       4703.79
6  Christopher Martinez           10       49465.57       3899.89
7         Keith Dawkins           28       27184.27       3038.63
8           Andy Reiter            9       26082.31       2884.62
9         Daniel Raglin           13       65092.94       2869.08

In [40]:
query = """
WITH customer_profit AS (
    SELECT 
        "Customer Name",
        SUM(Profit) AS Total_Profit
    FROM orders
    GROUP BY "Customer Name"
    ORDER BY Total_Profit DESC
)
SELECT 
    "Customer Name",
    ROUND(Total_Profit, 2) AS Total_Profit,
    ROUND(SUM(Total_Profit) OVER (ORDER BY Total_Profit DESC) * 100.0 / 
        (SELECT SUM(Total_Profit) FROM customer_profit), 2) AS Cumulative_Profit_Percent
FROM customer_profit
ORDER BY Total_Profit DESC
LIMIT 20;
"""
pd.read_sql(query, conn)

           Customer Name  Total_Profit  Cumulative_Profit_Percent
0           Tamara Chand       8981.32                       3.14
1           Raymond Buch       6976.10                       5.57
2           Sanjit Chand       5757.41                       7.58
3           Hunter Lopez       5622.43                       9.55
4          Adrian Barton       5444.81                      11.45
5           Tom Ashbrook       4703.79                      13.09
6   Christopher Martinez       3899.89                      14.45
7          Keith Dawkins       3038.63                      15.51
8            Andy Reiter       2884.62                      16.52
9          Daniel Raglin       2869.08                      17.52
10      Tom Boeckenhauer       2798.37                      18.50
11          Nathan Mautz       2751.68                      19.46
12          Sanjit Engle       2650.68                      20.38
13          Bill Shonely       2616.06                      21.30
14           Harry Marie       2437.98                      22.15
15          Todd Sumrall       2371.71                      22.98
16            Brian Moss       2199.28                      23.74
17    Christopher Conant       2177.05                      24.50
18             Jane Waco       2173.71                      25.26
19       Helen Wasserman       2164.16                      26.02

In [41]:
query = """
WITH customer_profit AS (
    SELECT 
        "Customer Name",
        SUM(Profit) AS Total_Profit
    FROM orders
    GROUP BY "Customer Name"
),
ranked AS (
    SELECT 
        "Customer Name",
        Total_Profit,
        SUM(Total_Profit) OVER (ORDER BY Total_Profit DESC) * 100.0 / 
            (SELECT SUM(Total_Profit) FROM customer_profit) AS Cumulative_Percent,
        ROW_NUMBER() OVER (ORDER BY Total_Profit DESC) AS Rank
    FROM customer_profit
)
SELECT MIN(Rank) AS Customers_Needed_For_80_Percent
FROM ranked
WHERE Cumulative_Percent >= 80;
"""
pd.read_sql(query, conn)

# total unique customers bhi nikal lete hain comparison ke liye
total_customers_query = 'SELECT COUNT(DISTINCT "Customer Name") AS Total_Customers FROM orders;'
pd.read_sql(total_customers_query, conn)

   Total_Customers
0              793